persistence:
  defaultStore: sqlite-default
  visibilityStore: sqlite-visibility
  datastores:
    sqlite-default:
      sql:
        pluginName: "sqlite"
        maxConns: 1
        maxIdleConns: 1
        maxConnLifetime: "128h"
        databaseName: "cadence.db"
    sqlite-visibility:
      sql:
        pluginName: "sqlite"
        maxConns: 1
        maxIdleConns: 1
        maxConnLifetime: "128h"
        databaseName: "cadence_visibility.db"
